/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/opennox/opennox/v1/cmd/opennox */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "main_android.go"

#define SDL_MAIN_HANDLED
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <ucontext.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <dlfcn.h>
#include <SDL2/SDL.h>
#include <android/log.h>

static void android_log(int prio, const char* tag, const char* msg) {
	__android_log_print(prio, tag, "%s", msg);
}

static void raw_crash_handler(int sig, siginfo_t* info, void* ucontext) {
	char buf[512];
	ucontext_t* uc = (ucontext_t*)ucontext;
	uintptr_t pc = 0, lr = 0, fault = (uintptr_t)info->si_addr;
#if defined(__arm__)
	pc = uc->uc_mcontext.arm_pc;
	lr = uc->uc_mcontext.arm_lr;
#elif defined(__aarch64__)
	pc = uc->uc_mcontext.pc;
	lr = uc->uc_mcontext.regs[30];
#endif
	const char* sym_pc = "?";
	const char* file_pc = "?";
	uintptr_t rel_pc = 0;
	Dl_info dli_pc;
	if (dladdr((void*)pc, &dli_pc)) {
		if (dli_pc.dli_sname) sym_pc = dli_pc.dli_sname;
		if (dli_pc.dli_fname) file_pc = dli_pc.dli_fname;
		if (dli_pc.dli_fbase) rel_pc = pc - (uintptr_t)dli_pc.dli_fbase;
	}

	const char* sym_lr = "?";
	const char* file_lr = "?";
	uintptr_t rel_lr = 0;
	Dl_info dli_lr;
	if (dladdr((void*)lr, &dli_lr)) {
		if (dli_lr.dli_sname) sym_lr = dli_lr.dli_sname;
		if (dli_lr.dli_fname) file_lr = dli_lr.dli_fname;
		if (dli_lr.dli_fbase) rel_lr = lr - (uintptr_t)dli_lr.dli_fbase;
	}

	int len = snprintf(buf, sizeof(buf),
		"\n\n*** FATAL NATIVE CRASH: signal %d (si_code=%d), fault addr=%p, PC=%p (+0x%lx in %s, sym=%s), LR=%p (+0x%lx in %s, sym=%s) ***\n\n",
		sig, info->si_code, (void*)fault, (void*)pc, (unsigned long)rel_pc, file_pc, sym_pc, (void*)lr, (unsigned long)rel_lr, file_lr, sym_lr);

	__android_log_print(ANDROID_LOG_FATAL, "OpenNoxCrash", "%s", buf);

	int fd = open("/sdcard/opennox/crash.log", O_WRONLY | O_CREAT | O_APPEND, 0666);
	if (fd >= 0) {
		write(fd, buf, len);
		close(fd);
	}
	int fd2 = open("/sdcard/opennox/opennox.log", O_WRONLY | O_CREAT | O_APPEND, 0666);
	if (fd2 >= 0) {
		write(fd2, buf, len);
		close(fd2);
	}
	_exit(128 + sig);
}

static void install_crash_handlers(void) {
	struct sigaction sa;
	memset(&sa, 0, sizeof(sa));
	sa.sa_sigaction = raw_crash_handler;
	sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
	sigaction(SIGSEGV, &sa, NULL);
	sigaction(SIGBUS, &sa, NULL);
	sigaction(SIGILL, &sa, NULL);
	sigaction(SIGFPE, &sa, NULL);
	sigaction(SIGABRT, &sa, NULL);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int SDL_main(int argc, char** argv);

#ifdef __cplusplus
}
#endif
